# **Logistic Regression Practice Notebook**

Dataset: **Titanic** (from the Seaborn library)

This notebook covers:
1. Univariate Logistic Regression
2. Multivariate Logistic Regression

Write your code in the empty cells below each question. Only a **Confusion Matrix** chart is required for each section — no other visualizations.

## **Section 1: Load and Prepare the Dataset**

**Q1.** Import the required libraries (`pandas`, `numpy`, `seaborn`, `matplotlib.pyplot`) and load the `titanic` dataset from Seaborn. Display the first 5 rows.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


**Q2.** Check the shape of the dataset, the data types of each column, and the count of missing values in each column.

In [3]:
print("Dataset Shape:", df.shape)
print("\nData Types and Non-Null Counts:")
df.info()

Dataset Shape: (891, 15)

Data Types and Non-Null Counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [4]:
print("\nMissing Values:")
print(df.isnull().sum())


Missing Values:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


**Q3.** Handle the missing values in the dataset appropriately (choose suitable columns to drop or fill).

In [5]:
# Check missing values
print(df.isnull().sum())

# 1. Fill Age with median
df['age'] = df['age'].fillna(df['age'].median())

# 2. Fill Embarked with mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

# 3. Fill Embark Town with mode
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])


# Verify
print("\nFinal dataset shape:", df.shape)
print("\nRemaining missing values:")
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Final dataset shape: (891, 15)

Remaining missing values:
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64


**Q4.** Identify the target variable for this task (`survived`) and confirm it is binary (0/1).

In [6]:
# Identify the target variable
target = 'survived'

# Check unique values
print("Unique values in target variable:")
print(df[target].unique())

# Check whether it is binary (0/1)
print("\nIs 'survived' binary (0/1)?")
print(set(df[target].unique()).issubset({0, 1}))

# Check the count of each class
print("\nTarget variable distribution:")
print(df[target].value_counts())

Unique values in target variable:
[0 1]

Is 'survived' binary (0/1)?
True

Target variable distribution:
survived
0    549
1    342
Name: count, dtype: int64


## **Section 2: Univariate Logistic Regression**

Use a single feature (`fare`) to predict `survived`.

**Q5.** Define `X` using only the `fare` column and `y` using the `survived` column.

In [7]:
X = df[['fare']]
y = df['survived']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (891, 1)
y shape: (891,)


**Q6.** Split the data into training and testing sets.

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

**Q7.** Build a Logistic Regression model and train it on the training data.

In [9]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression()
model.fit(X_train, y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


**Q8.** Predict the `survived` outcome for the test set.

In [10]:
Predicted_values = model.predict(X_test)

print("Predicted values:")
Predicted_values

Predicted values:


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

**Q9.** Calculate the accuracy of the model.

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy Score:", accuracy_score(y_test, Predicted_values))

Accuracy Score: 0.6536312849162011


**Q10.** Print the model's coefficient and intercept.

In [12]:
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [[0.01354448]]
Intercept: [-0.93002768]


**Q11.** Plot the Confusion Matrix for the univariate model. (Only this chart is required for this section — no other visualizations.)

In [13]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, Predicted_values))



Confusion Matrix:
[[100   5]
 [ 57  17]]


## **Section 3: Multivariate Logistic Regression**

Use multiple features (`pclass`, `age`, `fare`, `sibsp`, `sex`) to predict `survived`.

**Q12.** Encode any categorical column(s) needed among the chosen features (e.g., `sex`) into numeric form.

In [14]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['sex_encoded'] = encoder.fit_transform(df['sex'])
print(df[['sex', 'sex_encoded']].head())

      sex  sex_encoded
0    male            1
1  female            0
2  female            0
3  female            0
4    male            1


**Q13.** Define `X` using `pclass`, `age`, `fare`, `sibsp`, and the encoded `sex` column. Define `y` using `survived`.

In [15]:
X = df[['pclass', 'age', 'fare', 'sibsp', 'sex_encoded']]
y = df['survived']

**Q14.** Split the data into training and testing sets.

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

**Q15.** Build a Logistic Regression model and train it on the training data.

In [17]:
from sklearn.linear_model import LogisticRegression
model_multi = LogisticRegression(max_iter=1000)
model_multi.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


**Q16.** Predict the `survived` outcome for the test set.

In [23]:
Predicted_values_multi = model_multi.predict(X_test)
Predicted_values_multi

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0])

**Q17.** Calculate the accuracy of the model.

In [19]:
print("Accuracy Score:", accuracy_score(y_test, Predicted_values))

Accuracy Score: 0.8044692737430168


**Q18.** Print the model's coefficients and intercept. Identify which feature has the strongest influence.

In [20]:
print("Coefficients:", model_multi.coef_)
print("Intercept:", model_multi.intercept_)

Coefficients: [[-1.06754546 -0.03837451  0.00274496 -0.29277702 -2.57657569]]
Intercept: [4.66573159]


**Q19.** Plot the Confusion Matrix for the multivariate model. (Only this chart is required for this section — no other visualizations.)

In [24]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, Predicted_values_multi))


Confusion Matrix:
[[95 15]
 [20 49]]


**Q20.** Compare the accuracy of the univariate model (Section 2) with the multivariate model (Section 3). Which one performs better, and why do you think that is?

In [25]:
from sklearn.metrics import accuracy_score

# Accuracy of the univariate model
accuracy_uni = accuracy_score(y_test, Predicted_values_multi)

# Accuracy of the multivariate model
accuracy_multi = accuracy_score(y_test, Predicted_values_multi)

print("Univariate Model Accuracy:", accuracy_uni)
print("Multivariate Model Accuracy:", accuracy_multi)

Univariate Model Accuracy: 0.8044692737430168
Multivariate Model Accuracy: 0.8044692737430168
